Задание 1

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


Задание 2

In [4]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [6]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [7]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a.resize(12, 1)
print(a)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


Задание 3

In [12]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
np.reshape(a, (-1, 6))

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
np.reshape(a, (-1, 2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [15]:
a.reshape(4, -1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [16]:
a.reshape(12, -1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Задание 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - нет

In [17]:
a.ndim

2

Задание 5

In [18]:
a = np.random.randn(3, 4)
print(a)

[[ 1.00141039  0.43612254  0.05515125 -1.13601807]
 [-0.44345957  1.09699545  1.02144426 -0.62148433]
 [-0.04839327  2.01677435  1.05638243  0.35252886]]


In [21]:
b = a.flatten()
print(b)

[ 1.00141039  0.43612254  0.05515125 -1.13601807 -0.44345957  1.09699545
  1.02144426 -0.62148433 -0.04839327  2.01677435  1.05638243  0.35252886]


In [22]:
a.size == b.size

True

Задание 6

In [27]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


Задание 7

In [30]:
b = np.arange(20, 0, -2)
print(b)

[20 18 16 14 12 10  8  6  4  2]


In [31]:
np.array_equal(a, b)

True

Задание 8

In [37]:
a = np.zeros((2, 2))
print('Массив а', a, sep = '\n')
b = np.ones((3, 2))
print('Массив в', b, sep = '\n')

Массив а
[[0. 0.]
 [0. 0.]]
Массив в
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [40]:
v = np.concatenate((a, b), axis = 0)
print(z)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [41]:
v.size

10

Задание 9

In [42]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [54]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [55]:
At = A.T
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [56]:
B = np.dot(A, At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [57]:
B.size

16

In [58]:
np.linalg.det(B)

0.0

Вычислить обратную матрицу для B невозможно, т.к. определитель матрицы B равен 0.

Задание 10

In [84]:
np.random.seed(42)

Задание 11

In [60]:
a = np.arange(0, 16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Задание 12

In [61]:
np.sqrt(a.size)

4.0

In [62]:
C = a.reshape(4, 4)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [64]:
D = C * 10 + B
print(D)

[[  5  24  43  62]
 [ 54 100 146 192]
 [103 176 249 322]
 [152 252 352 452]]


In [65]:
np.linalg.det(D)

-7.685903354004529e-25

In [77]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 1.10382344e+13  5.26315789e-02 -3.31147031e+13  2.20764688e+13]
 [-8.46264636e+13  9.38249922e+13  6.62294063e+13 -7.54279349e+13]
 [ 1.36138224e+14 -1.87649984e+14 -3.31147031e+13  8.46264636e+13]
 [-6.25499948e+13  9.38249922e+13  0.00000000e+00 -3.12749974e+13]]


In [69]:
np.linalg.matrix_rank(D)

2

Задание 13

In [80]:
D_positive = D_inv > 0
D_negative = D_inv < 0
D_inv[D_positive] = 1
D_inv[D_negative] = 0
print(D_inv)

[[1. 1. 0. 1.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [0. 1. 0. 0.]]


In [81]:
E = np.where(D_inv, B, C)
print(E)

[[  5  14   2  32]
 [  4  50  86   7]
 [ 23   9  10 212]
 [ 12 122  14  15]]
